apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      service: django
  template:
    metadata:
      labels:
        service: django
    spec:
      containers:
       - name: django-service
         image: abedulwahed/backend:latest
         imagePullPolicy: Always
         env:
          - name: POSTGRES_PASSWORD
            value: mysecretpassword
         ports:
          - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: service-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    service: django
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30001
